// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5Ntix7h-xu4FvSPNaoDTeXbV6cHO7KUM',
    appId: '1:681482688095:web:bd5ea5bd357e7af5c72dea',
    messagingSenderId: '681482688095',
    projectId: 'zoom-clone-flutter-9201f',
    authDomain: 'zoom-clone-flutter-9201f.firebaseapp.com',
    storageBucket: 'zoom-clone-flutter-9201f.appspot.com',
    measurementId: 'G-HLBXD9GF59',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjp5iRkceKCRYolimn2A4S_IKoaWQjYT4',
    appId: '1:681482688095:android:f4ece727f5ddbac7c72dea',
    messagingSenderId: '681482688095',
    projectId: 'zoom-clone-flutter-9201f',
    storageBucket: 'zoom-clone-flutter-9201f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1pJ-D44RSC3KxuJQWOfmKSD7iqKO09QA',
    appId: '1:681482688095:ios:05d5d4836c121646c72dea',
    messagingSenderId: '681482688095',
    projectId: 'zoom-clone-flutter-9201f',
    storageBucket: 'zoom-clone-flutter-9201f.appspot.com',
    iosClientId: '681482688095-ui4m9hp5eauooetpln50igrf0k7mvetq.apps.googleusercontent.com',
    iosBundleId: 'com.example.zoomCloneTutorial',
  );
}
